# Generated by Django 4.2.1 on 2023-05-21 13:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.FileField(blank=True, null=True, upload_to='')),
                ('topic', models.CharField(max_length=2500, null=True)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('motivation', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('introduction', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('background_of_study', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('statement_of_problem', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('aim_and_objective_of_the_study', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('methodology', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('software_developement_tools', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('scope_of_the_study', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('significance_of_the_study', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('project_topic_views', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
